baseURL = "https://secondpost.d2bcmd6okt9e8w.amplifyapp.com/"
languageCode = "en-us"
title = "Serverless Site Example"
# Edit your config.toml configuration file
# and add the Ananke theme.
theme = "ananke"
