baseURL = "https://secondpost.d1iwwwakr4m9k3.amplifyapp.com/"
languageCode = "en-us"
title = "Tony's hugo site"
# Edit your config.toml configuration file
# and add the Ananke theme.
theme = "ananke"
